name: Release
on:
    release:
        types:
            - published
jobs:
    register:
        name: Package, Publish, and Register
        runs-on:
            - ubuntu-latest
        steps:
            - id: checkout
              name: Checkout code
              uses: actions/checkout@v3
            - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
              name: Login to GitHub Package Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GHCR_TOKEN }}
            - id: setup-tools
              uses: buildpacks/github-actions/setup-tools@v5.7.3
            - id: setup-pack
              uses: buildpacks/github-actions/setup-pack@v5.7.3
            - id: package
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                BP_ID="$(cat buildpack.toml | yj -t | jq -r .buildpack.id)"
                VERSION="$(cat buildpack.toml | yj -t | jq -r .buildpack.version)"
                BP_ID_SNAKECASE=$(echo "$BP_ID" | sed 's/\//_/g')
                PACKAGE="${REPO}/$BP_ID_SNAKECASE"
                BP_FILE="${BP_ID_SNAKECASE}-${VERSION}.cnb"
                pack buildpack package --publish ${PACKAGE}:${VERSION}
                pack buildpack package --format file $BP_FILE
                DIGEST="$(crane digest ${PACKAGE}:${VERSION})"
                echo "bp_id=$BP_ID" >> "$GITHUB_OUTPUT"
                echo "version=$VERSION" >> "$GITHUB_OUTPUT"
                echo "address=${PACKAGE}@${DIGEST}" >> "$GITHUB_OUTPUT"
                echo "file=$BP_FILE" >> "$GITHUB_OUTPUT"
              shell: bash
              env:
                REPO: ghcr.io/${{ github.repository_owner }}/buildpacks
            - id: update-release
              run: |
                #!/usr/bin/env bash
                set -euo pipefail
                curl -X POST \
                  -H "Authorization: token $GHCR_TOKEN" \
                  -H "Content-Type: $(file -b --mime-type $BP_FILE)" \
                  --data-binary @$BP_FILE \
                  "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${VERSION}/assets?name=${BP_FILE}"
              env:
                GHCR_TOKEN:   ${{ secrets.GHCR_TOKEN }}
                BP_FILE: ${{ steps.package.outputs.file }}
                VERSION: ${{ steps.package.outputs.version }}
            - id: register
              uses: docker://ghcr.io/buildpacks/actions/registry/request-add-entry:5.7.3
              with:
                token:   ${{ secrets.PUBLIC_REPO_TOKEN }}
                id:      ${{ steps.package.outputs.bp_id }}
                version: ${{ steps.package.outputs.version }}
                address: ${{ steps.package.outputs.address }}